from typing import Any

# Type alias for values returned from Perl.
# At runtime, these are Python-native types (str, int, float, bool, list, dict, None).
type PerlValue = str | int | float | bool | list[Any] | dict[str, Any] | None

def hello_from_bin() -> str: ...

class PerlInterpreter:
    """Low-level Perl interpreter wrapper."""

    def __init__(self) -> None: ...
    def use_module(self, module_name: str) -> None: ...
    def call_method(
        self, module: str, method: str, args: list[object]
    ) -> PerlValue: ...
    def call_function(self, function_name: str, args: list[object]) -> PerlValue: ...
    def eval(self, code: str) -> PerlValue: ...
